--- #YAML:1.0
name:                Carp-REPL
version:             0.05
abstract:            read-eval-print-loop on die
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Devel::REPL:                   0
    Lexical::Persistence:          0
    Moose:                         0
    Moose::Role:                   0
    namespace::clean:              0
    PadWalker:                     0
    Test::Expect:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Shawn M Moore <sartak@gmail.com>
