---
abstract: 'read-eval-print-loop on die and/or warn'
author:
  - 'Shawn M Moore, C<< <sartak at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Expect: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-REPL
no_index:
  directory:
    - inc
    - t
  package:
    - DB
    - Devel::REPL::Plugin::Carp::REPL
requires:
  Data::Dump::Streamer: 0
  Devel::LexAlias: 0
  Devel::REPL: 0
  Devel::StackTrace::WithLexicals: 0
  Lexical::Persistence: 0
  namespace::clean: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bestpractical/carp-repl
version: 0.15
