--- 
abstract: read-eval-print-loop on die
author: Shawn M Moore, C<< <sartak at gmail.com> >>
build_requires: 
  Test::Expect: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Carp-REPL
no_index: 
  directory: 
    - inc
    - t
requires: 
  Devel::LexAlias: 0
  Devel::REPL: 0
  Moose: 0
  Moose::Role: 0
  PadWalker: 0
  namespace::clean: 0
version: 0.09
